Remove faulty `reinterpret_cast`
This wrongly casts a `const uintptr_t` to `uintptr_t` which "is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast" (MSVC error C2440)

In fact no cast is required at that point, just remove it